// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxatzwhfdvptdniymjvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4YXR6d2hmZHZwdGRuaXltanZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNjUxMzEsImV4cCI6MjA1NTc0MTEzMX0.fY66NnwrltQs4vUYf0L4vuf3wVkKFTuSEQHO57MQH0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);